### Concatenation in Pandas

`pd.concat()` is used when you want to **stack DataFrames together**.

Think of it like:

* Stack vertically (add more rows)
* Stack horizontally (add more columns)

It does NOT match based on keys like `merge()` does.

That’s the core difference.

---

#### Row-wise Concatenation (Default)

This stacks rows.

```python
pd.concat([df_jan, df_feb])
```

What happens?

* Rows from df_feb are added below df_jan
* Index continues (0,1,2,0,1,2)

Important:
Index is NOT automatically reset.

---

#### ignore_index=True

If you want clean indexing:

```python
pd.concat([df_jan, df_feb], ignore_index=True)
```

Now index becomes:

0,1,2,3,4,5

This is what you usually want in real workflows.

---

#### Column-wise Concatenation (axis=1)

Now suppose we have:

```python
df_customer = pd.DataFrame({
    "Customer": ["A", "B", "C"]
})
```

If we do:

```python
pd.concat([df_jan, df_customer], axis=1)
```

What happens?

* Columns are added side by side.
* Pandas aligns rows based on index.

This is VERY important.

If indexes don’t match, you get NaN.

Concatenation aligns by index automatically.

---

#### Handling Mismatched Columns

Let’s break it intentionally.

```python
df_mar = pd.DataFrame({
    "OrderID": [7, 8],
    "Category": ["Home", "Clothing"],
    "Discount": [10, 20]
})
```

Now:

```python
pd.concat([df_jan, df_mar], ignore_index=True)
```

What happens?

* `Amount` missing in df_mar → NaN
* `Discount` missing in df_jan → NaN

Pandas fills missing columns with NaN automatically.

This is expected behavior.

Brutal truth:
If you don’t inspect after concat, you may silently introduce NaNs.

Always check:

```python
df.isna().sum()
```

after concatenation.

---

#### keys= (Creates Hierarchical Index)

This is powerful.

```python
pd.concat([df_jan, df_feb], keys=["January", "February"])
```

Now you get a MultiIndex:

Level 1 → Month
Level 2 → Original index

This is useful when stacking multiple similar datasets but still want to know origin.

Later helpful in time-series or grouped analysis.

---

In [1]:
import pandas as pd

df_jan = pd.DataFrame({
    "OrderID": [1, 2, 3],
    "Category": ["Electronics", "Clothing", "Home"],
    "Amount": [15000, 2000, 5000]
})

df_feb = pd.DataFrame({
    "OrderID": [4, 5, 6],
    "Category": ["Clothing", "Electronics", "Home"],
    "Amount": [3000, 18000, 7000]
})

In [ ]:
# Row wise Concatenation (Vertical Concatenation)
pd.concat([df_jan, df_feb]) # Index is NOT automatically reset.

   OrderID     Category  Amount
0        1  Electronics   15000
1        2     Clothing    2000
2        3         Home    5000
0        4     Clothing    3000
1        5  Electronics   18000
2        6         Home    7000

In [3]:
pd.concat([df_jan, df_feb], ignore_index=True)

   OrderID     Category  Amount
0        1  Electronics   15000
1        2     Clothing    2000
2        3         Home    5000
3        4     Clothing    3000
4        5  Electronics   18000
5        6         Home    7000

In [4]:
df_customer = pd.DataFrame({
    "Customer": ["A", "B", "C"]
})

In [5]:
# Column Wise Concatenation (Horizontal Stacking)

pd.concat([df_jan, df_customer],axis = 1)

   OrderID     Category  Amount Customer
0        1  Electronics   15000        A
1        2     Clothing    2000        B
2        3         Home    5000        C

In [8]:
# Handling mismatched columns

df_mar = pd.DataFrame({
    "OrderID": [7, 8],
    "Category": ["Home", "Clothing"],
    "Discount": [10, 20]
})

pd.concat([df_jan, df_mar], ignore_index=True)

   OrderID     Category   Amount  Discount
0        1  Electronics  15000.0       NaN
1        2     Clothing   2000.0       NaN
2        3         Home   5000.0       NaN
3        7         Home      NaN      10.0
4        8     Clothing      NaN      20.0

In [9]:
pd.concat([df_jan, df_feb], keys=["January", "February"])

            OrderID     Category  Amount
January  0        1  Electronics   15000
         1        2     Clothing    2000
         2        3         Home    5000
February 0        4     Clothing    3000
         1        5  Electronics   18000
         2        6         Home    7000