### Pivot Table

#### pivot()

`pivot()` reshapes data.

It requires:

* One column for index
* One column for columns
* One column for values

Basic example:

```python
df.pivot(index="Date", columns="Store", values="Sales")
```

What happens?

Rows → Date
Columns → Store
Values → Sales

It rearranges into matrix form.

---

#### Important Rule

`pivot()` FAILS if duplicate combinations exist.

In our dataset:

For Date = 2024-01-03
Store = A
There are TWO Phone entries.

So:

```python
df.pivot(index="Date", columns="Store", values="Sales")
```

Will raise:

> ValueError: Index contains duplicate entries

Because pivot needs unique (index, column) pairs.

No aggregation allowed.

---

#### pivot_table() (Smarter Version)

`pivot_table()` handles duplicates using aggregation.

Same idea:

```python
df.pivot_table(
    index="Date",
    columns="Store",
    values="Sales"
)
```

By default:
Aggregation = mean

So duplicate entries get averaged.

This is why `pivot_table()` is safer in real projects.

---

#### Handling Duplicates Explicitly

You can define aggregation:

```python
df.pivot_table(
    index="Date",
    columns="Store",
    values="Sales",
    aggfunc="sum"
)
```

Now duplicates get summed instead of averaged.

---

#### Multiple Aggregation Functions

```python
df.pivot_table(
    index="Store",
    values="Sales",
    aggfunc=["mean","max","min"]
)
```

Now you get hierarchical columns:

mean → Sales
max → Sales
min → Sales

This is powerful for summary reports.

---

#### Multiple Index & Columns

You can increase dimensionality.

```python
df.pivot_table(
    index=["Date","Product"],
    columns="Store",
    values="Sales",
    aggfunc="sum"
)
```

Now rows become hierarchical:

Date → Product

This is advanced reshaping.

---

#### fill_value=

By default, missing combinations → NaN.

You can replace them:

```python
df.pivot_table(
    index="Date",
    columns="Store",
    values="Sales",
    aggfunc="sum",
    fill_value=0
)
```

Very useful when preparing ML features.

Models don’t like NaN.

---

#### margins=True (Totals)

Adds totals automatically.

```python
df.pivot_table(
    index="Store",
    values="Sales",
    aggfunc="sum",
    margins=True
)
```

Adds:

All → grand total

Very useful for quick sanity checks.

---

In [1]:
import pandas as pd

data = {
    "Date": ["2024-01-01","2024-01-01","2024-01-02","2024-01-02",
             "2024-01-03","2024-01-03","2024-01-03"],
    "Store": ["A","B","A","B","A","B","A"],
    "Product": ["Laptop","Laptop","Laptop","Laptop",
                "Phone","Phone","Phone"],
    "Sales": [50000,40000,55000,42000,20000,18000,22000]
}

df = pd.DataFrame(data)
df

         Date Store Product  Sales
0  2024-01-01     A  Laptop  50000
1  2024-01-01     B  Laptop  40000
2  2024-01-02     A  Laptop  55000
3  2024-01-02     B  Laptop  42000
4  2024-01-03     A   Phone  20000
5  2024-01-03     B   Phone  18000
6  2024-01-03     A   Phone  22000

In [4]:
try:
    df.pivot(index="Date",columns="Store",values="Sales")
except ValueError:
    print("Dataframe Has Duplicate Entry")
# This will give error due to duplicate entries

Dataframe Has Duplicate Entry

In [5]:
# the best way to handle this is to use aggregation function
df.pivot_table(
    index="Date",
    columns="Store",
    values="Sales",
    aggfunc="sum"
)

Store           A      B
Date
2024-01-01  50000  40000
2024-01-02  55000  42000
2024-01-03  42000  18000

In [6]:
df.pivot_table(
    index="Store",
    values="Sales",
    aggfunc=["mean","max","min"]
)

               mean    max    min
              Sales  Sales  Sales
Store
A      36750.000000  55000  20000
B      33333.333333  42000  18000