In [1]:
import pandas as pd
import numpy as np

data = {
    "OrderID": range(1, 16),
    "Category": [
        "Electronics", "Clothing", "Electronics", "Home",
        "Clothing", "Electronics", "Home", "Clothing",
        "Electronics", "Home", "Clothing", "Clothing",
        "Electronics", np.nan, "Home"
    ],
    "PaymentMethod": [
        "UPI", "Card", "UPI", "Cash",
        "Card", "UPI", "Cash", "Card",
        "Card", "Cash", "UPI", "Card",
        "UPI", "UPI", "Cash"
    ],
    "Amount": [
        15000, 2000, 12000, 5000,
        2500, 18000, 7000, 3000,
        22000, 4500, 2800, 3500,
        16000, 9000, 6000
    ]
}

df = pd.DataFrame(data)
df

    OrderID     Category PaymentMethod  Amount
0         1  Electronics           UPI   15000
1         2     Clothing          Card    2000
2         3  Electronics           UPI   12000
3         4         Home          Cash    5000
4         5     Clothing          Card    2500
5         6  Electronics           UPI   18000
6         7         Home          Cash    7000
7         8     Clothing          Card    3000
8         9  Electronics          Card   22000
9        10         Home          Cash    4500
10       11     Clothing           UPI    2800
11       12     Clothing          Card    3500
12       13  Electronics           UPI   16000
13       14          NaN           UPI    9000
14       15         Home          Cash    6000

In [2]:
df.sort_values("Amount")

    OrderID     Category PaymentMethod  Amount
1         2     Clothing          Card    2000
4         5     Clothing          Card    2500
10       11     Clothing           UPI    2800
7         8     Clothing          Card    3000
11       12     Clothing          Card    3500
9        10         Home          Cash    4500
3         4         Home          Cash    5000
14       15         Home          Cash    6000
6         7         Home          Cash    7000
13       14          NaN           UPI    9000
2         3  Electronics           UPI   12000
0         1  Electronics           UPI   15000
12       13  Electronics           UPI   16000
5         6  Electronics           UPI   18000
8         9  Electronics          Card   22000

In [3]:
df.sort_values("Amount", ascending=False)

    OrderID     Category PaymentMethod  Amount
8         9  Electronics          Card   22000
5         6  Electronics           UPI   18000
12       13  Electronics           UPI   16000
0         1  Electronics           UPI   15000
2         3  Electronics           UPI   12000
13       14          NaN           UPI    9000
6         7         Home          Cash    7000
14       15         Home          Cash    6000
3         4         Home          Cash    5000
9        10         Home          Cash    4500
11       12     Clothing          Card    3500
7         8     Clothing          Card    3000
10       11     Clothing           UPI    2800
4         5     Clothing          Card    2500
1         2     Clothing          Card    2000

In [4]:
df.sort_values("Category")

    OrderID     Category PaymentMethod  Amount
1         2     Clothing          Card    2000
4         5     Clothing          Card    2500
7         8     Clothing          Card    3000
10       11     Clothing           UPI    2800
11       12     Clothing          Card    3500
0         1  Electronics           UPI   15000
2         3  Electronics           UPI   12000
5         6  Electronics           UPI   18000
8         9  Electronics          Card   22000
12       13  Electronics           UPI   16000
3         4         Home          Cash    5000
6         7         Home          Cash    7000
9        10         Home          Cash    4500
14       15         Home          Cash    6000
13       14          NaN           UPI    9000

In [5]:
df.sort_values(["Category", "Amount"], ascending=[True, False])

    OrderID     Category PaymentMethod  Amount
11       12     Clothing          Card    3500
7         8     Clothing          Card    3000
10       11     Clothing           UPI    2800
4         5     Clothing          Card    2500
1         2     Clothing          Card    2000
8         9  Electronics          Card   22000
5         6  Electronics           UPI   18000
12       13  Electronics           UPI   16000
0         1  Electronics           UPI   15000
2         3  Electronics           UPI   12000
6         7         Home          Cash    7000
14       15         Home          Cash    6000
3         4         Home          Cash    5000
9        10         Home          Cash    4500
13       14          NaN           UPI    9000

In [ ]:
df.sort_values("Category", na_position="first") # it can be last also

    OrderID     Category PaymentMethod  Amount
13       14          NaN           UPI    9000
1         2     Clothing          Card    2000
4         5     Clothing          Card    2500
7         8     Clothing          Card    3000
10       11     Clothing           UPI    2800
11       12     Clothing          Card    3500
0         1  Electronics           UPI   15000
2         3  Electronics           UPI   12000
5         6  Electronics           UPI   18000
8         9  Electronics          Card   22000
12       13  Electronics           UPI   16000
3         4         Home          Cash    5000
6         7         Home          Cash    7000
9        10         Home          Cash    4500
14       15         Home          Cash    6000

In [7]:
# Sorting keeps the row index same as original if you want reset it as per new sorting then
df.sort_values("Amount").reset_index(drop=True)

    OrderID     Category PaymentMethod  Amount
0         2     Clothing          Card    2000
1         5     Clothing          Card    2500
2        11     Clothing           UPI    2800
3         8     Clothing          Card    3000
4        12     Clothing          Card    3500
5        10         Home          Cash    4500
6         4         Home          Cash    5000
7        15         Home          Cash    6000
8         7         Home          Cash    7000
9        14          NaN           UPI    9000
10        3  Electronics           UPI   12000
11        1  Electronics           UPI   15000
12       13  Electronics           UPI   16000
13        6  Electronics           UPI   18000
14        9  Electronics          Card   22000

In [8]:
df.sort_index()

    OrderID     Category PaymentMethod  Amount
0         1  Electronics           UPI   15000
1         2     Clothing          Card    2000
2         3  Electronics           UPI   12000
3         4         Home          Cash    5000
4         5     Clothing          Card    2500
5         6  Electronics           UPI   18000
6         7         Home          Cash    7000
7         8     Clothing          Card    3000
8         9  Electronics          Card   22000
9        10         Home          Cash    4500
10       11     Clothing           UPI    2800
11       12     Clothing          Card    3500
12       13  Electronics           UPI   16000
13       14          NaN           UPI    9000
14       15         Home          Cash    6000

In [9]:
df.sort_index(axis=1)

    Amount     Category  OrderID PaymentMethod
0    15000  Electronics        1           UPI
1     2000     Clothing        2          Card
2    12000  Electronics        3           UPI
3     5000         Home        4          Cash
4     2500     Clothing        5          Card
5    18000  Electronics        6           UPI
6     7000         Home        7          Cash
7     3000     Clothing        8          Card
8    22000  Electronics        9          Card
9     4500         Home       10          Cash
10    2800     Clothing       11           UPI
11    3500     Clothing       12          Card
12   16000  Electronics       13           UPI
13    9000          NaN       14           UPI
14    6000         Home       15          Cash