### GroupBy Operations

#### groupby() — Single Column Grouping

Basic idea:

Split → Apply → Combine

Group students by Department:

```python
df.groupby("Department")["Marks"].mean()
```

What happens?

* CS students grouped
* IT students grouped
* Mean calculated per group

Output shape:
Small summary table.

---

#### Multi-Column Grouping

Group by Department AND Gender:

```python
df.groupby(["Department", "Gender"])["Marks"].mean()
```

Now you get hierarchical index:

Department → Gender → Value

This is how real segmentation works.

---

#### Basic Aggregations

```python
df.groupby("Department")["Marks"].sum()
df.groupby("Department")["Marks"].max()
df.groupby("Department")["Marks"].min()
```

Simple. But real work needs more.

---

#### agg() — Multiple Aggregations

```python
df.groupby("Department")["Marks"].agg(["mean", "max", "min"])
```

Now you get multiple stats at once.

Much cleaner than separate lines.

---

#### Named Aggregation (Professional Way)

Cleaner and production-friendly:

```python
df.groupby("Department").agg(
    avg_marks=("Marks", "mean"),
    highest_marks=("Marks", "max"),
    avg_attendance=("Attendance", "mean")
)
```

Now column names are meaningful.

This is how you write clean analysis.

---

#### size() vs count()

Important difference.

```python
df.groupby("Department").size()
```

Counts total rows per group.

Now:

```python
df.groupby("Department")["Marks"].count()
```

Counts non-null values in Marks column.

If Marks had NaN, count() would ignore them.
size() would not.

Brutal truth:
Most people don’t know this difference.

---

#### transform() (VERY IMPORTANT)

This does NOT reduce shape.

Example:

Add department average marks to each student.

```python
df["Dept_Avg_Marks"] = df.groupby("Department")["Marks"].transform("mean")
```

Now each row still exists.

Shape remains 10 rows.

---

#### Difference: agg() vs transform()

`agg()` → Reduces rows
`transform()` → Keeps original shape

Example:

```python
df.groupby("Department")["Marks"].mean()
```

Output → 2 rows

But:

```python
df.groupby("Department")["Marks"].transform("mean")
```

Output → 10 rows

---

#### filter()

Filter groups based on condition.

Example:

Keep only departments with average marks > 85

```python
df.groupby("Department").filter(
    lambda x: x["Marks"].mean() > 85
)
```

This returns full rows of qualifying groups.

Powerful for removing weak segments.

---

In [1]:
import pandas as pd
import numpy as np

data = {
    "Student": ["A","B","C","D","E","F","G","H","I","J"],
    "Department": ["CS","CS","IT","IT","CS","IT","CS","IT","CS","IT"],
    "Gender": ["M","F","F","M","M","F","F","M","M","F"],
    "Marks": [85, 78, 92, 70, 88, 95, 60, 75, 82, 89],
    "Attendance": [90, 85, 95, 80, 88, 96, 70, 78, 84, 91]
}

df = pd.DataFrame(data)

df

  Student Department Gender  Marks  Attendance
0       A         CS      M     85          90
1       B         CS      F     78          85
2       C         IT      F     92          95
3       D         IT      M     70          80
4       E         CS      M     88          88
5       F         IT      F     95          96
6       G         CS      F     60          70
7       H         IT      M     75          78
8       I         CS      M     82          84
9       J         IT      F     89          91

In [ ]:
# Single Column Grouping
df.groupby("Department")["Marks"].mean()

# You get department wise average total marks

Department
CS    78.6
IT    84.2
Name: Marks, dtype: float64

In [8]:
# Multicolumn Grouping
df.groupby(["Department","Gender"])["Marks"].mean()

Department  Gender
CS          F         69.0
            M         85.0
IT          F         92.0
            M         72.5
Name: Marks, dtype: float64

In [ ]:
df.groupby("Department")["Marks"].min()
# Here you will get department wise minimum marks

"""
sum() -> will give you sum of all marks
max() -> will give you maximum of all marks
mean() -> will give you average of all marks

this is a basic aggregation
"""

Department
CS    60
IT    70
Name: Marks, dtype: int64

In [11]:
# Multiple aggregation together
df.groupby("Department")["Marks"].agg(["mean","max","min"])

            mean  max  min
Department
CS          78.6   88   60
IT          84.2   95   70

In [12]:
# When we do multiple aggregation what we put a name to that column
df.groupby("Department").agg(
    avg_marks=("Marks", "mean"),
    highest_marks=("Marks", "max"),
    avg_attendance=("Attendance", "mean")
)

            avg_marks  highest_marks  avg_attendance
Department
CS               78.6             88            83.4
IT               84.2             95            88.0

In [15]:
df["Dept_Avg_Marks"] = df.groupby("Department")["Marks"].transform("mean")
# It creates a new column adds the result of aggregation of respective department to that column
df

  Student Department Gender  Marks  Attendance  Dept_Avg_Marks
0       A         CS      M     85          90            78.6
1       B         CS      F     78          85            78.6
2       C         IT      F     92          95            84.2
3       D         IT      M     70          80            84.2
4       E         CS      M     88          88            78.6
5       F         IT      F     95          96            84.2
6       G         CS      F     60          70            78.6
7       H         IT      M     75          78            84.2
8       I         CS      M     82          84            78.6
9       J         IT      F     89          91            84.2

In [ ]:
# Filter Function

# Example : Keep only departments with average marks > 85

# Aggregation is on "Departments columns"
# res = df.groupby("Department") 

# We want department wise average marks but the average has to be greater than 85
# res.filter(lambda x : x["Marks"].mean() > 85) 

df.groupby("Department").filter(
    lambda x: x["Marks"].mean() > 50
)

""" 
for each department_group:
    take subset dataframe
    apply lambda
    if True:
        keep whole group
    else:
        discard whole group
"""

  Student Department Gender  Marks  Attendance  Dept_Avg_Marks
0       A         CS      M     85          90            78.6
1       B         CS      F     78          85            78.6
2       C         IT      F     92          95            84.2
3       D         IT      M     70          80            84.2
4       E         CS      M     88          88            78.6
5       F         IT      F     95          96            84.2
6       G         CS      F     60          70            78.6
7       H         IT      M     75          78            84.2
8       I         CS      M     82          84            78.6
9       J         IT      F     89          91            84.2