In [2]:
# Create a data set
import pandas as pd

data = {
    "user_id": [1,2,3,4,5,6],
    "age": [22, 35, 28, 45, 31, 52],
    "gender": ["Male","Female","male","Female","Mle","Male"],
    "city": ["Mumbai","Delhi","Mumbai","Bangalore","Delhi","Mumbai"],
    "signup_date": [
        "2024-01-01",
        "2024-02-15",
        "2024-02-20",
        "2024-03-05",
        "2024-03-18",
        "2024-04-01"
    ],
    "salary": [40000,60000,52000,80000,58000,120000]
}

df = pd.DataFrame(data)

df["signup_date"] = pd.to_datetime(df["signup_date"])

df

   user_id  age  gender       city signup_date  salary
0        1   22    Male     Mumbai  2024-01-01   40000
1        2   35  Female      Delhi  2024-02-15   60000
2        3   28    male     Mumbai  2024-02-20   52000
3        4   45  Female  Bangalore  2024-03-05   80000
4        5   31     Mle      Delhi  2024-03-18   58000
5        6   52    Male     Mumbai  2024-04-01  120000

#### Phase 3 : Feature Engineering Basics

#### Phase 3.1 — Creating New Columns

This is the MOST important habit.

#### Example 1 — Interaction Feature

```python
df["salary_per_age"] = df["salary"] / df["age"]
```

Why?

Models often learn better from ratios than raw numbers.

---

#### Example 2 — Date Features

```python
df["signup_month"] = df["signup_date"].dt.month
df["signup_dayofweek"] = df["signup_date"].dt.dayofweek
```

---

#### Phase 3.2 — `map()` and `replace()` (Preferred over apply)

You already saw messy gender values:

```
Male, male, Mle
```

Normalize first.

```python
df["gender"] = df["gender"].str.lower()

df["gender"] = df["gender"].replace({
    "mle": "male"
})
```

Now convert categories into numbers:

```python
df["gender_encoded"] = df["gender"].map({
    "male": 1,
    "female": 0
})
```

Why `map()`?

👉 Fast
👉 Clean
👉 Vectorized

---

#### Phase 3.3 — Controlled use of `apply()`

Use only when vectorized logic doesn’t exist.

Example: classify salary level.

```python
def salary_level(x):
    if x < 50000:
        return "low"
    elif x < 80000:
        return "medium"
    else:
        return "high"

df["salary_level"] = df["salary"].apply(salary_level)
```

But remember:

👉 If pandas has built-in methods, prefer them.

---

#### Phase 3.4 — One-Hot Encoding (Just Know this we will learn it soon)

Convert categories into ML-friendly format.

```python
df = pd.get_dummies(df, columns=["city"], dtype=int)
```

Now you’ll see:

```
city_Mumbai
city_Delhi
city_Bangalore
```

This is extremely common before training models.

---

#### Phase 3.5 — Binning (cut / qcut)

Turning continuous numbers into groups.

#### Equal-width bins

```python
df["age_group"] = pd.cut(
    df["age"],
    bins=[0,30,50,100],
    labels=["young","adult","senior"]
)
```

---

#### Quantile bins (balanced groups)

```python
df["salary_quantile"] = pd.qcut(df["salary"], q=3)
```

This creates bins with roughly equal counts.

Very useful when distributions are skewed.

---

In [3]:
# Creating new columns from existing columns

# getting salary per age
df["salary_per_age"] = df["salary"] / df["age"]

df["signup_month"] = df["signup_date"].dt.month
df["signup_dayofweek"] = df["signup_date"].dt.dayofweek

df

,user_id,age,gender,city,signup_date,salary,salary_per_age,signup_month,signup_dayofweek
0,1,22,Male,Mumbai,2024-01-01,40000,1818.181818,1,0
1,2,35,Female,Delhi,2024-02-15,60000,1714.285714,2,3
2,3,28,male,Mumbai,2024-02-20,52000,1857.142857,2,1
3,4,45,Female,Bangalore,2024-03-05,80000,1777.777778,3,1
4,5,31,Mle,Delhi,2024-03-18,58000,1870.967742,3,0
5,6,52,Male,Mumbai,2024-04-01,120000,2307.692308,4,0

In [4]:
# Replace Function

# Gender -> Male, male, Mle

df["gender"] = df["gender"].str.lower()

df["gender"] = df["gender"].replace({
    "mle": "male"
})

df

,user_id,age,gender,city,signup_date,salary,salary_per_age,signup_month,signup_dayofweek
0,1,22,male,Mumbai,2024-01-01,40000,1818.181818,1,0
1,2,35,female,Delhi,2024-02-15,60000,1714.285714,2,3
2,3,28,male,Mumbai,2024-02-20,52000,1857.142857,2,1
3,4,45,female,Bangalore,2024-03-05,80000,1777.777778,3,1
4,5,31,male,Delhi,2024-03-18,58000,1870.967742,3,0
5,6,52,male,Mumbai,2024-04-01,120000,2307.692308,4,0

In [5]:
# Map Function

df["gender_encoded"] = df["gender"].map({
    "male": 1,
    "female": 0
})

df

,user_id,age,gender,city,signup_date,salary,salary_per_age,signup_month,signup_dayofweek,gender_encoded
0,1,22,male,Mumbai,2024-01-01,40000,1818.181818,1,0,1
1,2,35,female,Delhi,2024-02-15,60000,1714.285714,2,3,0
2,3,28,male,Mumbai,2024-02-20,52000,1857.142857,2,1,1
3,4,45,female,Bangalore,2024-03-05,80000,1777.777778,3,1,0
4,5,31,male,Delhi,2024-03-18,58000,1870.967742,3,0,1
5,6,52,male,Mumbai,2024-04-01,120000,2307.692308,4,0,1

In [7]:
# Apply Function

def salary_level(x):
    if x < 50000:
        return "low"
    elif x < 80000:
        return "medium"
    else:
        return "high"

df["salary_level"] = df["salary"].apply(salary_level)

df

,user_id,age,gender,city,signup_date,salary,salary_per_age,signup_month,signup_dayofweek,gender_encoded,salary_level
0,1,22,male,Mumbai,2024-01-01,40000,1818.181818,1,0,1,low
1,2,35,female,Delhi,2024-02-15,60000,1714.285714,2,3,0,medium
2,3,28,male,Mumbai,2024-02-20,52000,1857.142857,2,1,1,medium
3,4,45,female,Bangalore,2024-03-05,80000,1777.777778,3,1,0,high
4,5,31,male,Delhi,2024-03-18,58000,1870.967742,3,0,1,medium
5,6,52,male,Mumbai,2024-04-01,120000,2307.692308,4,0,1,high

In [ ]:
pd.get_dummies(df, columns=["city"], dtype=int)

,user_id,age,gender,signup_date,salary,salary_per_age,signup_month,signup_dayofweek,gender_encoded,salary_level,city_Bangalore,city_Delhi,city_Mumbai
0,1,22,male,2024-01-01,40000,1818.181818,1,0,1,low,0,0,1
1,2,35,female,2024-02-15,60000,1714.285714,2,3,0,medium,0,1,0
2,3,28,male,2024-02-20,52000,1857.142857,2,1,1,medium,0,0,1
3,4,45,female,2024-03-05,80000,1777.777778,3,1,0,high,1,0,0
4,5,31,male,2024-03-18,58000,1870.967742,3,0,1,medium,0,1,0
5,6,52,male,2024-04-01,120000,2307.692308,4,0,1,high,0,0,1

In [16]:
df["age_group"] = pd.cut(
    df["age"],
    bins=[0,30,50,100],
    labels=["young","adult","senior"]
)

df

,user_id,age,gender,signup_date,salary,salary_per_age,signup_month,signup_dayofweek,gender_encoded,salary_level,city_Bangalore,city_Delhi,city_Mumbai,age_group
0,1,22,male,2024-01-01,40000,1818.181818,1,0,1,low,0,0,1,young
1,2,35,female,2024-02-15,60000,1714.285714,2,3,0,medium,0,1,0,adult
2,3,28,male,2024-02-20,52000,1857.142857,2,1,1,medium,0,0,1,young
3,4,45,female,2024-03-05,80000,1777.777778,3,1,0,high,1,0,0,adult
4,5,31,male,2024-03-18,58000,1870.967742,3,0,1,medium,0,1,0,adult
5,6,52,male,2024-04-01,120000,2307.692308,4,0,1,high,0,0,1,senior

In [18]:
df["salary_quantile"] = pd.qcut(df["salary"], q=3)
df

,user_id,age,gender,signup_date,salary,salary_per_age,signup_month,signup_dayofweek,gender_encoded,salary_level,city_Bangalore,city_Delhi,city_Mumbai,age_group,salary_quantile
0,1,22,male,2024-01-01,40000,1818.181818,1,0,1,low,0,0,1,young,"(39999.999, 56000.0]"
1,2,35,female,2024-02-15,60000,1714.285714,2,3,0,medium,0,1,0,adult,"(56000.0, 66666.667]"
2,3,28,male,2024-02-20,52000,1857.142857,2,1,1,medium,0,0,1,young,"(39999.999, 56000.0]"
3,4,45,female,2024-03-05,80000,1777.777778,3,1,0,high,1,0,0,adult,"(66666.667, 120000.0]"
4,5,31,male,2024-03-18,58000,1870.967742,3,0,1,medium,0,1,0,adult,"(56000.0, 66666.667]"
5,6,52,male,2024-04-01,120000,2307.692308,4,0,1,high,0,0,1,senior,"(66666.667, 120000.0]"