### Merge and Joins

####  INNER JOIN

```python id="7sjx2a"
pd.merge(users, orders, on="UserID", how="inner")
```

Meaning:

Keep only matching keys in both tables.

Result:
Only UserID 1,2,3 remain.

Users 4 & 5 removed.
Orders 6 & 7 removed.

Inner = intersection.

---

####  LEFT JOIN

```python id="ozl6hf"
pd.merge(users, orders, on="UserID", how="left")
```

Meaning:

Keep ALL users.
Attach matching orders.

Users 4 & 5 → Amount becomes NaN.

Left = preserve left table.

Very common in ML feature building.

---

#### RIGHT JOIN

```python id="8sazn0"
pd.merge(users, orders, on="UserID", how="right")
```

Meaning:

Keep ALL orders.
Attach matching user info.

Orders with UserID 6 & 7 → Name & City become NaN.

Right = preserve right table.

Used less frequently.

---

#### OUTER JOIN

```python id="1qvbnm"
pd.merge(users, orders, on="UserID", how="outer")
```

Meaning:

Keep everything from both tables.

Missing matches → NaN.

Union of keys.

---

#### Join Behavior Summary

Inner → common only
Left → all left
Right → all right
Outer → everything

If you don’t know which one you need, stop and think.

---

#### Merge on Multiple Keys

Example:

Let’s modify orders:

```python id="3nbz8f"
orders2 = pd.DataFrame({
    "UserID": [1,2,2,3],
    "City": ["Delhi","Mumbai","Delhi","Pune"],
    "Amount": [5000,2000,3000,7000]
})
```

Now merge on two columns:

```python id="h3b9dn"
pd.merge(users, orders2, on=["UserID","City"], how="inner")
```

Now matching requires BOTH columns to match.

Much stricter.

---

#### Different Column Names

Example:

```python id="c9g8rk"
orders_renamed = orders.rename(columns={"UserID":"CustomerID"})
```

Now:

```python id="w8z1tp"
pd.merge(users, orders_renamed,
         left_on="UserID",
         right_on="CustomerID",
         how="inner")
```

Useful when column names differ.

---

In [9]:
import pandas as pd

users = pd.DataFrame({
    "UserID": [1,2,3,4,5],
    "Name": ["A","B","C","D","E"],
    "City": ["Delhi","Mumbai","Pune","Delhi","Chennai"]
})

orders = pd.DataFrame({
    "OrderID": [101,102,103,104,105,106],
    "UserID": [1,2,2,3,6,7],
    "Amount": [5000,2000,3000,7000,4000,1000]
})

In [ ]:
pd.merge(users, orders, on="UserID", how="inner")
# returns only matching rows

   UserID Name    City  OrderID  Amount
0       1    A   Delhi      101    5000
1       2    B  Mumbai      102    2000
2       2    B  Mumbai      103    3000
3       3    C    Pune      104    7000

In [3]:
# Left Join
pd.merge(users, orders, on="UserID", how="left")
# returns all the rows from users and only matching rows from orders

   UserID Name     City  OrderID  Amount
0       1    A    Delhi    101.0  5000.0
1       2    B   Mumbai    102.0  2000.0
2       2    B   Mumbai    103.0  3000.0
3       3    C     Pune    104.0  7000.0
4       4    D    Delhi      NaN     NaN
5       5    E  Chennai      NaN     NaN

In [10]:
# Right Join

pd.merge(users, orders, on="UserID", how="right")

   UserID Name    City  OrderID  Amount
0       1    A   Delhi      101    5000
1       2    B  Mumbai      102    2000
2       2    B  Mumbai      103    3000
3       3    C    Pune      104    7000
4       6  NaN     NaN      105    4000
5       7  NaN     NaN      106    1000

In [11]:
# Outer Join -> returns all rows from both data frames
pd.merge(users, orders, on="UserID", how="outer")

   UserID Name     City  OrderID  Amount
0       1    A    Delhi    101.0  5000.0
1       2    B   Mumbai    102.0  2000.0
2       2    B   Mumbai    103.0  3000.0
3       3    C     Pune    104.0  7000.0
4       4    D    Delhi      NaN     NaN
5       5    E  Chennai      NaN     NaN
6       6  NaN      NaN    105.0  4000.0
7       7  NaN      NaN    106.0  1000.0

In [12]:
orders2 = pd.DataFrame({
    "UserID": [1,2,2,3],
    "City": ["Delhi","Mumbai","Delhi","Pune"],
    "Amount": [5000,2000,3000,7000]
})

pd.merge(users, orders2, on=["UserID","City"], how="inner")

   UserID Name    City  Amount
0       1    A   Delhi    5000
1       2    B  Mumbai    2000
2       3    C    Pune    7000

In [13]:
orders_renamed = orders.rename(columns={"UserID":"CustomerID"})

pd.merge(users, orders_renamed,
         left_on="UserID",
         right_on="CustomerID",
         how="inner")

   UserID Name    City  OrderID  CustomerID  Amount
0       1    A   Delhi      101           1    5000
1       2    B  Mumbai      102           2    2000
2       2    B  Mumbai      103           2    3000
3       3    C    Pune      104           3    7000

# MultiIndexing 

#### Dataset — Company Employees

```python
import pandas as pd

data = {
    "Department": ["IT","IT","HR","HR","Sales","Sales"],
    "Role": ["Dev","Manager","Recruiter","Manager","Executive","Manager"],
    "Employee": ["A","B","C","D","E","F"],
    "Salary": [80000,120000,60000,95000,50000,70000]
}

df = pd.DataFrame(data)
```

---

#### `set_index()`

Convert columns into index.

#### Single Index

```python
df.set_index("Department")
```

Now Department is no longer a column — it becomes row index.

---

#### MultiIndex (Hierarchical Index)

```python
df_multi = df.set_index(["Department","Role"])
```

Now index has two levels:

Level 1 → Department
Level 2 → Role

This is hierarchical indexing.

Internally it becomes something like:

```
IT       Dev        A   80000
         Manager    B   120000
HR       Recruiter  C   60000
         Manager    D   95000
Sales    Executive  E   50000
         Manager    F   70000
```

You didn’t create new data.
You just changed structure.

---

####  Selecting & Slicing MultiIndex

This is where people panic. Don’t.

---

#### Select entire department

```python
df_multi.loc["IT"]
```

Returns all roles under IT.

---

#### Select specific department + role

```python
df_multi.loc[("IT","Dev")]
```

This gives one row.

Important:
When selecting multiple levels → use tuple.

---

#### Slice multiple departments

```python
df_multi.loc[["IT","HR"]]
```

Works like normal indexing.

---

####  `reset_index()`

Undo the hierarchy.

```python
df_multi.reset_index()
```

MultiIndex becomes normal columns again.

---